# SPDX-FileCopyrightText: 2026 Lokesh Selvam <lokeshselvam7025@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only

"""Hook specification for OpenCode.

OpenCode uses in-process JS/TS plugins for session telemetry.
Plugins subscribe to events like session.idle, message.updated, etc.
This module provides metadata for `observal doctor patch` and the
plugin source that gets installed into .opencode/plugins/.

Bump HOOKS_SPEC_VERSION whenever the plugin definition changes.
"""

from __future__ import annotations

HOOKS_SPEC_VERSION = "1"

# OpenCode plugin events used for telemetry:
# - session.created: session started (initialization)
# - session.idle: session finished responding (push final data)
# - message.updated: a message was added/updated (incremental push)
OPENCODE_HOOK_EVENTS = ("session.created", "session.idle", "message.updated")


def build_hooks() -> dict:
    """Return hook metadata for OpenCode.

    OpenCode's hooks are delivered as a plugin file placed in
    .opencode/plugins/ or ~/.config/opencode/plugins/.
    The plugin subscribes to session lifecycle events and pushes
    message data to the Observal server.
    """
    return {
        "hook_type": "plugin",
        "install_method": "file",
        "plugin_path": ".opencode/plugins/observal-plugin.ts",
        "global_plugin_path": "~/.config/opencode/plugins/observal-plugin.ts",
        "events": list(OPENCODE_HOOK_EVENTS),
    }


def get_plugin_source() -> str:
    """Return the TypeScript plugin source for OpenCode telemetry.

    This plugin:
    1. On session.created: initializes tracking state
    2. On message.updated: buffers message updates
    3. On session.idle: flushes all buffered messages to the Observal server

    Uses the OpenCode SDK client (available in plugin context) to read
    session messages, then POSTs them to the Observal ingest endpoint.
    """
    return """// Observal telemetry plugin for OpenCode
// Auto-generated by `observal pull` / `observal doctor patch`
// Do not edit manually - regenerated on upgrade.

import { execFileSync, execSync } from "child_process";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

const CONFIG_PATH = join(
  process.env.HOME || process.env.USERPROFILE || "~",
  ".observal",
  "config.json"
);

function loadConfig() {
  try {
    if (!existsSync(CONFIG_PATH)) return null;
    const raw = readFileSync(CONFIG_PATH, "utf-8");
    const cfg = JSON.parse(raw);
    if (!cfg.server_url || !cfg.access_token) return null;
    return cfg;
  } catch {
    return null;
  }
}

function pushToServer(payload) {
  const config = loadConfig();
  if (!config) return;

  const url = `${config.server_url}/api/v1/ingest/session`;
  const body = JSON.stringify(payload);

  try {
    // Use curl for HTTP POST to avoid needing node-fetch
    execFileSync("curl", [
      "-s", "-X", "POST",
      "-H", "Content-Type: application/json",
      "-H", `Authorization: Bearer ${config.access_token}`,
      "--max-time", "10",
      "-d", body,
      url,
    ], { stdio: ["pipe", "pipe", "pipe"], timeout: 12000 });
  } catch {
    // Non-blocking: never break the session
  }
}

// Track state per session
const sessionState = new Map();

function getState(sessionId) {
  if (!sessionState.has(sessionId)) {
    sessionState.set(sessionId, {
      pushedMessageIds: new Set(),
      lineOffset: 0,
    });
  }
  return sessionState.get(sessionId);
}

function messagesToLines(messages) {
  // Convert OpenCode messages to Claude-Code-compatible JSONL format
  // so the existing ingest pipeline can classify them.
  const lines = [];
  for (const msg of messages) {
    const info = msg.info || msg;
    const parts = msg.parts || [];

    const content = [];
    for (const part of parts) {
      if (part.type === "text") {
        content.push({ type: "text", text: part.text || "" });
      } else if (part.type === "tool-invocation" || part.type === "tool_use") {
        content.push({
          type: "tool_use",
          id: part.toolInvocationId || part.id || "",
          name: part.toolName || part.name || "",
          input: part.args || part.input || {},
        });
      } else if (part.type === "tool-result" || part.type === "tool_result") {
        content.push({
          type: "tool_result",
          tool_use_id: part.toolInvocationId || part.tool_use_id || "",
          content: part.result || part.content || "",
        });
      } else if (part.type === "reasoning" || part.type === "thinking") {
        content.push({ type: "thinking", thinking: part.text || part.thinking || "" });
      }
    }

    const role = info.role || "assistant";
    // Extract timestamp - OpenCode uses {created: epoch_ms, completed: epoch_ms}
    let ts = new Date().toISOString();
    if (info.createdAt && typeof info.createdAt === "string") {
      ts = info.createdAt;
    } else if (info.time && typeof info.time === "object" && info.time.created) {
      ts = new Date(info.time.created).toISOString();
    } else if (info.time && typeof info.time === "string") {
      ts = info.time;
    } else if (info.timestamp && typeof info.timestamp === "string") {
      ts = info.timestamp;
    }
    const line = {
      type: role === "user" ? "user" : "assistant",
      timestamp: ts,
      uuid: info.id || "",
      parentUuid: info.parentID || info.parentId || "",
      message: {
        role: role,
        content: content,
        model: info.modelID || info.model || "",
      },
    };

    // Add token usage if available
    if (info.tokens || info.usage) {
      const usage = info.tokens || info.usage || {};
      line.message.usage = {
        input_tokens: usage.input || usage.inputTokens || 0,
        output_tokens: usage.output || usage.outputTokens || 0,
        cache_read_input_tokens: usage.cacheRead || usage.cacheReadTokens || 0,
        cache_creation_input_tokens: usage.cacheWrite || usage.cacheWriteTokens || 0,
      };
    }

    lines.push(JSON.stringify(line));
  }
  return lines;
}

export const ObservalPlugin = async ({ project, client, directory }) => {
  return {
    "session.created": async ({ event }) => {
      // Initialize state for this session
      const sessionId = event?.properties?.id || event?.id || "";
      if (sessionId) {
        getState(sessionId);
      }
    },

    "session.idle": async ({ event }) => {
      // Session finished responding - push all messages
      const sessionId = event?.properties?.id || event?.id || "";
      if (!sessionId) return;

      try {
        const messagesResult = await client.session.messages({
          path: { id: sessionId },
        });
        const messages = messagesResult?.data || messagesResult || [];
        if (!Array.isArray(messages) || messages.length === 0) return;

        const state = getState(sessionId);
        // Only push messages we haven't pushed yet
        const newMessages = messages.filter(
          (m) => !state.pushedMessageIds.has(m.info?.id || m.id)
        );
        if (newMessages.length === 0) return;

        const lines = messagesToLines(newMessages);
        if (lines.length === 0) return;

        pushToServer({
          session_id: sessionId,
          ide: "opencode",
          lines: lines,
          start_offset: state.lineOffset,
          hook_event: "session.idle",
          final: true,
          total_line_count: state.lineOffset + lines.length,
          total_offset: state.lineOffset + lines.length,
        });

        // Update state
        for (const m of newMessages) {
          state.pushedMessageIds.add(m.info?.id || m.id);
        }
        state.lineOffset += lines.length;
      } catch {
        // Non-blocking
      }
    },

    "message.updated": async ({ event }) => {
      // Incremental push on each message update
      const sessionId = event?.properties?.sessionID || event?.sessionId || "";
      const messageId = event?.properties?.id || event?.id || "";
      if (!sessionId || !messageId) return;

      const state = getState(sessionId);
      if (state.pushedMessageIds.has(messageId)) return;

      try {
        const msgResult = await client.session.message({
          path: { id: sessionId, messageId: messageId },
        });
        const msg = msgResult?.data || msgResult;
        if (!msg) return;

        const lines = messagesToLines([msg]);
        if (lines.length === 0) return;

        pushToServer({
          session_id: sessionId,
          ide: "opencode",
          lines: lines,
          start_offset: state.lineOffset,
          hook_event: "message.updated",
          final: false,
        });

        state.pushedMessageIds.add(messageId);
        state.lineOffset += lines.length;
      } catch {
        // Non-blocking
      }
    },
  };
};
"""
